server:
  port: 8889
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true


spring:
  config:
    import: "optional:configserver:"
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
  application:
    name: service_1
