server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            file:\\\D:\Java\Programmes\java advanced\task_5.1.4\ms-config-properties\{application}\{profile}
  application:
    name: config-server


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}